theme: minima
title: IKIM web site
description: Institute for AI in Medicine / University Hospital Essen / University of Duisburg-Essen / Germany
baseurl: /ikim-website
twitter_username: IkimUme
github_username: IKIM-Essen
plugins: ['jekyll/scholar']
scholar:
  source: /_bibliography
  bibliography: '**/*.bib{,tex}'
  repository: /pdfs
  style: chicago-fullnote-bibliography
  group_by: year
  group_order: descending
  sort_by: year,month
  order: descending
  bibliography_template: bib
