name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: Install ruby and dependencies
      run: sudo apt-get install -y ruby-full build-essential zlib1g-dev
    - name: Create and configure a local gem directory
      run: mkdir -p $HOME/gems && export GEM_HOME="$HOME/gems" && export PATH="$HOME/gems/bin:$PATH"
    - name: Install bundler
      run: sudo gem install bundler
    - name: Install jekyll and the rest of the dependencies
      run: bundle install
    - name: Run the jekyll build
      run: jekyll build
    - name: Upload the created pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        name: "github-pages"
        path: "_site/"
        retention_days: "1"
  
  publish:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
