name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Build
      uses: docker://jekyll/builder:stable
      with:
        entrypoint: bundle && jekyll build
    - name: Upload the created pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        name: "github-pages"
        path: "_site/"
        retention-days: "1"
  
  publish:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
